namespace LocalAiAssistantService.Dtos.Models
{
    /// <summary>
    /// Represents the request payload sent to the Gemmini model service.
    /// </summary>
    public class GemminiRequestDto
    {
        /// <summary>
        /// The model identifier (e.g. "gemma:2b").
        /// </summary>
        public string Model { get; set; } = "gemma:2b";

        /// <summary>
        /// The text prompt to send to the model.
        /// </summary>
        public string Prompt { get; set; } = string.Empty;

        /// <summary>
        /// Optional temperature value for response randomness (0–1).
        /// </summary>
        public double? Temperature { get; set; }

        /// <summary>
        /// Optional maximum number of tokens to generate.
        /// </summary>
        public int? MaxTokens { get; set; }
    }



    /// <summary>
    /// Represents the response received from the Gemmini model service.
    /// </summary>
    public class GemminiResponseDto
    {
        /// <summary>
        /// Whether the request was processed successfully.
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        /// The textual response generated by the model.
        /// </summary>
        public string Response { get; set; } = string.Empty;

        /// <summary>
        /// Optional error message if something went wrong.
        /// </summary>
        public string? Error { get; set; }
    }
}
